### ISSUE TITLE
Hide empty letters

### ISSUE THREAD

**Issue by billymedia** [bowlhat/wp-a-z-listing#21]
Is there a way to hide letters with no posts from the `<?php $a_z_query->the_letters(); ?>` output? Kinda like hide_empty.

**Comment by diddledan** [comment]
There is no way to do this right now. I will try to remember to get it into a future version soon.

**Comment by billymedia** [comment]
ok thanks!

**Comment by diddledan** [comment]
you can do this with CSS now. The output will include classes on the letters of `has-posts` for letters that have associated posts, and `no-posts` for letters that do not. You can therefore include some CSS similar to:

```css
ul.az-links li.no-posts {
    display: none;
}
```
