### ISSUE TITLE
how to list articles in a specific category

### ISSUE THREAD

**Issue by tncyrdmc** [bowlhat/wp-a-z-listing#27]
how to list articles in a specific category?

Thanks

**Comment by diddledan** [comment]
for "posts" categorised in the "categories" of `Term ID=5` you would use a shortcode similar to:

```plain
[a-z-listing post-type="post" taxonomy="category" terms="5"]
```

You can get your term ID from the address when you edit the term in `admin->posts->categories->[your term]` where you will get to an address of the form:

```https://example.com/wp-admin/term.php?taxonomy=category&tag_ID=5&post_type=post&wp_http_referer=%2Fwp-admin%2Fedit-tags.php%3Ftaxonomy%3Dcategory```

Here the term ID is `5` which is shown in the address where it reads `tag_ID=5`.
