### ISSUE TITLE
How to get the Current Item's Post ID

### ISSUE THREAD

**Issue by realnsleo** [bowlhat/wp-a-z-listing#33]
Hi, first off awesome plugin! I am having a problem getting the Post ID of the current item in the loop. For example in this code snippet:

```
<ul class="columns max-<?php echo $column_limit; ?>-columns">
	<?php
		while ( $a_z_query->have_items() ) :
			$a_z_query->the_item();
                        echo the_ID(); // I use this to see if I can get the ID of the_item
	?>
	<li>
		<a href="<?php $a_z_query->the_permalink(); ?>"><?php $a_z_query->the_title(); ?> <?php echo $brackets ?></a>
	</li>
	<?php endwhile; ?>
</ul>
```
Above, when I output `the_ID()` I instead get the ID of the page that is calling the shortcode. Is there a way to get the current item ID? I must be missing something. Any help is greatly appreciated.

Regards,

**Comment by diddledan** [comment]
Hi,

Right now the way to get the ID is to call `$a_z_query->get_the_item_object( 'I understand the issues!' );` inside the loop and then call `the_ID()` or `get_the_ID()` as you already tried. The reason for the extra step, and the parameter passed as `I understand the issues!` (which must state exactly that text as the value, including the exclamation point), is that on large listing pages loading every post object into memory might be slow and memory intensive so I've tried to shave a bit of time and memory by not doing it directly.

I'll take this as a feature request to add a new function (which I will do so in the next release) that you can use directly on the `$a_z_query` object to fetch the ID without loading the full `WP_Post` into memory.

**Comment by diddledan** [comment]
The code would be similar to:

```php
<ul class="columns max-<?php echo $column_limit; ?>-columns">
	<?php
		while ( $a_z_query->have_items() ) :
			$a_z_query->the_item();
                        $a_z_query->get_the_item_object( 'I understand the issues!' );
                        echo get_the_ID();
	?>
	<li>
		<a href="<?php $a_z_query->the_permalink(); ?>"><?php $a_z_query->the_title(); ?> <?php echo $brackets ?></a>
	</li>
	<?php endwhile; ?>
</ul>
```

**Comment by realnsleo** [comment]
Thanks so much!
I'll take that into consideration. Thanks for the great work!
